package com.dwb.stuffoflegend.database.core;

public enum QueryKey {
	CREATE_USER, LOGIN, GET_TRACKS, GET_ABILITY_TYPES, GET_PROGRESSIONS, GET_TRACKS_FOR_CLASS, GET_CIRCLES_FOR_TRACK, GET_CLASSES, CREATE_CLASS, TRANSLATE_CLASS, LAST_INSERTED_ID, CREATE_ABILITY, TRANSLATE_ABILITY, CREATE_TRACK, CREATE_CIRCLE, CREATE_CIRCLE_CHOICE, ;
}
